{
  "id":39,
  "name":"fbuch_datemailinglist",
  "formtabs":"",
  "contextmenus":"",
  "actionbuttons":"",
  "columnbuttons":"",
  "filters":"",
  "extended":{
    "migx_add":"",
    "disable_add_item":"",
    "add_items_directly":"",
    "formcaption":"",
    "update_win_title":"",
    "win_id":"fbuch_datemailinglist",
    "maxRecords":"",
    "addNewItemAt":"bottom",
    "media_source_id":"",
    "multiple_formtabs":"",
    "multiple_formtabs_label":"",
    "multiple_formtabs_field":"",
    "multiple_formtabs_optionstext":"",
    "multiple_formtabs_optionsvalue":"",
    "actionbuttonsperrow":4,
    "winbuttonslist":"",
    "extrahandlers":"",
    "filtersperrow":4,
    "packageName":"fbuch",
    "classname":"fbuchMailinglistNames",
    "task":"",
    "getlistsort":"",
    "getlistsortdir":"",
    "sortconfig":"",
    "gridpagesize":"",
    "use_custom_prefix":"0",
    "prefix":"",
    "grid":"",
    "gridload_mode":2,
    "check_resid":"0",
    "check_resid_TV":"",
    "join_alias":"",
    "has_jointable":"no",
    "getlistwhere":"{\"list_id\":\"[[migxLoopCollection? &packageName=`fbuch` &classname=`fbuchDate` &where=`{\"id\":\"[[+object_id]]\"}` &tpl=`@CODE:[[+mailinglist_id]]`]]\"}",
    "joins":[
      {
        "alias":"Member"
      }
    ],
    "hooksnippets":"",
    "cmpmaincaption":"",
    "cmptabcaption":"",
    "cmptabdescription":"",
    "cmptabcontroller":"",
    "winbuttons":"",
    "onsubmitsuccess":"",
    "submitparams":""
  },
  "columns":[
    {
      "MIGX_id":7,
      "dataIndex":"Member_name",
      "header":"Member_name"
    },
    {
      "MIGX_id":8,
      "dataIndex":"Member_firstname",
      "header":"Member_firstname"
    },
    {
      "MIGX_id":10,
      "dataIndex":"subscribed",
      "header":"subscribed"
    },
    {
      "MIGX_id":11,
      "dataIndex":"unsubscribed",
      "header":"unsubscribed"
    }
  ],
  "createdby":1,
  "createdon":"2020-01-19 18:09:33",
  "editedby":1,
  "editedon":"2020-01-19 18:35:23",
  "deleted":0,
  "deletedon":"-1-11-30 00:00:00",
  "deletedby":0,
  "published":1,
  "publishedon":"-1-11-30 00:00:00",
  "publishedby":0,
  "category":""
}