{
  "id":44,
  "name":"fbuch_dateinvites",
  "formtabs":"",
  "contextmenus":"",
  "actionbuttons":"",
  "columnbuttons":"",
  "filters":"",
  "extended":{
    "migx_add":"",
    "disable_add_item":"",
    "add_items_directly":"",
    "formcaption":"",
    "update_win_title":"",
    "win_id":"fbuch_dateinvites",
    "maxRecords":"",
    "addNewItemAt":"bottom",
    "media_source_id":"",
    "multiple_formtabs":"",
    "multiple_formtabs_label":"",
    "multiple_formtabs_field":"",
    "multiple_formtabs_optionstext":"",
    "multiple_formtabs_optionsvalue":"",
    "actionbuttonsperrow":4,
    "winbuttonslist":"",
    "extrahandlers":"",
    "filtersperrow":4,
    "packageName":"fbuch",
    "classname":"fbuchDateInvited",
    "task":"",
    "getlistsort":"",
    "getlistsortdir":"",
    "sortconfig":"",
    "gridpagesize":"",
    "use_custom_prefix":"0",
    "prefix":"",
    "grid":"",
    "gridload_mode":2,
    "check_resid":1,
    "check_resid_TV":"",
    "join_alias":"Date",
    "has_jointable":"no",
    "getlistwhere":"",
    "joins":[
      {
        "alias":"Member"
      }
    ],
    "hooksnippets":"",
    "cmpmaincaption":"",
    "cmptabcaption":"",
    "cmptabdescription":"",
    "cmptabcontroller":"",
    "winbuttons":"",
    "onsubmitsuccess":"",
    "submitparams":""
  },
  "columns":[
    {
      "MIGX_id":7,
      "dataIndex":"Member_name",
      "header":"Member_name"
    },
    {
      "MIGX_id":8,
      "dataIndex":"Member_firstname",
      "header":"Member_firstname"
    },
    {
      "MIGX_id":3,
      "dataIndex":"canceled",
      "header":"canceled"
    },
    {
      "MIGX_id":4,
      "dataIndex":"invited",
      "header":"invited"
    },
    {
      "MIGX_id":5,
      "dataIndex":"riot_state",
      "header":"riot_state"
    }
  ],
  "createdby":1,
  "createdon":"2020-01-19 16:55:09",
  "editedby":1,
  "editedon":"2020-01-19 16:59:54",
  "deleted":0,
  "deletedon":"-1-11-30 00:00:00",
  "deletedby":0,
  "published":1,
  "publishedon":"-1-11-30 00:00:00",
  "publishedby":0,
  "category":""
}