{
  "id":33,
  "name":"fbuch_mailinglistnames",
  "formtabs":"",
  "contextmenus":"",
  "actionbuttons":"",
  "columnbuttons":"",
  "filters":"",
  "extended":{
    "migx_add":"",
    "disable_add_item":"",
    "add_items_directly":"",
    "formcaption":"",
    "update_win_title":"",
    "win_id":"fbuch_mailinglistnames",
    "maxRecords":"",
    "addNewItemAt":"bottom",
    "media_source_id":"",
    "multiple_formtabs":"",
    "multiple_formtabs_label":"",
    "multiple_formtabs_field":"",
    "multiple_formtabs_optionstext":"",
    "multiple_formtabs_optionsvalue":"",
    "actionbuttonsperrow":4,
    "winbuttonslist":"",
    "extrahandlers":"",
    "filtersperrow":4,
    "packageName":"fbuch",
    "classname":"fbuchMailinglistNames",
    "task":"",
    "getlistsort":"Member.name",
    "getlistsortdir":"",
    "sortconfig":"",
    "gridpagesize":"",
    "use_custom_prefix":"0",
    "prefix":"",
    "grid":"",
    "gridload_mode":2,
    "check_resid":1,
    "check_resid_TV":"",
    "join_alias":"Mailinglist",
    "has_jointable":"no",
    "getlistwhere":"",
    "joins":[
      {
        "alias":"Member"
      }
    ],
    "hooksnippets":"",
    "cmpmaincaption":"",
    "cmptabcaption":"",
    "cmptabdescription":"",
    "cmptabcontroller":"",
    "winbuttons":"",
    "onsubmitsuccess":"",
    "submitparams":""
  },
  "columns":[
    {
      "MIGX_id":3,
      "dataIndex":"Member_name",
      "header":"Member_name"
    },
    {
      "MIGX_id":2,
      "dataIndex":"Member_firstname",
      "header":"Member_firstname"
    },
    {
      "MIGX_id":4,
      "dataIndex":"unsubscribed",
      "header":"unsubscribed"
    },
    {
      "MIGX_id":5,
      "dataIndex":"subscribed",
      "header":"subscribed"
    },
    {
      "MIGX_id":6,
      "dataIndex":"id",
      "header":"id"
    }
  ],
  "createdby":1,
  "createdon":"2018-06-03 20:42:50",
  "editedby":1,
  "editedon":"2018-06-04 06:24:51",
  "deleted":0,
  "deletedon":"-1-11-30 00:00:00",
  "deletedby":0,
  "published":1,
  "publishedon":"-1-11-30 00:00:00",
  "publishedby":0,
  "category":""
}