{
  "id":56,
  "name":"fbuch_anmeldungen",
  "formtabs":"",
  "contextmenus":"",
  "actionbuttons":"",
  "columnbuttons":"",
  "filters":[
    {
      "MIGX_id":1,
      "name":"anmeldung_lastname",
      "label":"",
      "emptytext":"Nachname",
      "type":"combobox",
      "getlistwhere":{
        "Member.name":"[[+anmeldung_lastname]]"
      },
      "getcomboprocessor":"getcombo",
      "combotextfield":"Member.name",
      "comboidfield":"",
      "combowhere":"",
      "comboclassname":"",
      "combopackagename":"",
      "combo_use_custom_prefix":"0",
      "comboprefix":"",
      "combojoins":"",
      "comboparent":"",
      "default":""
    },
    {
      "MIGX_id":2,
      "name":"anmeldung_firstname",
      "label":"",
      "emptytext":"Vorname",
      "type":"combobox",
      "getlistwhere":{
        "Member.firstname":"[[+anmeldung_firstname]]"
      },
      "getcomboprocessor":"getcombo",
      "combotextfield":"Member.firstname",
      "comboidfield":"",
      "combowhere":{
        "Member.name":"[[+anmeldung_lastname]]"
      },
      "comboclassname":"",
      "combopackagename":"",
      "combo_use_custom_prefix":"0",
      "comboprefix":"",
      "combojoins":"",
      "comboparent":"anmeldung_lastname",
      "default":""
    }
  ],
  "extended":{
    "migx_add":"",
    "disable_add_item":"",
    "add_items_directly":"",
    "formcaption":"",
    "update_win_title":"",
    "win_id":"fbuch_anmeldungen",
    "maxRecords":"",
    "addNewItemAt":"bottom",
    "media_source_id":"",
    "multiple_formtabs":"",
    "multiple_formtabs_label":"",
    "multiple_formtabs_field":"",
    "multiple_formtabs_optionstext":"",
    "multiple_formtabs_optionsvalue":"",
    "actionbuttonsperrow":4,
    "winbuttonslist":"",
    "extrahandlers":"",
    "filtersperrow":4,
    "packageName":"fbuch",
    "classname":"fbuchDateNames",
    "task":"",
    "getlistsort":"",
    "getlistsortdir":"",
    "sortconfig":[
      {
        "sortby":"Date.date",
        "sortdir":"DESC"
      }
    ],
    "gridpagesize":"",
    "use_custom_prefix":"0",
    "prefix":"",
    "grid":"",
    "gridload_mode":1,
    "check_resid":1,
    "check_resid_TV":"",
    "join_alias":"",
    "has_jointable":"yes",
    "getlistwhere":"",
    "joins":[
      {
        "alias":"Member"
      },
      {
        "alias":"Date"
      }
    ],
    "hooksnippets":"",
    "cmpmaincaption":"",
    "cmptabcaption":"Anmeldungen",
    "cmptabdescription":"Anmeldungen verwalten",
    "cmptabcontroller":"",
    "winbuttons":"",
    "onsubmitsuccess":"",
    "submitparams":""
  },
  "columns":[
    {
      "MIGX_id":2,
      "header":"id",
      "dataIndex":"id",
      "width":"",
      "sortable":true,
      "show_in_grid":1,
      "customrenderer":"",
      "renderer":"",
      "clickaction":"",
      "selectorconfig":"",
      "renderchunktpl":"",
      "renderoptions":"",
      "editor":""
    },
    {
      "MIGX_id":4,
      "dataIndex":"Date_title",
      "header":"Date_title"
    },
    {
      "MIGX_id":5,
      "dataIndex":"Date_date",
      "header":"Date_date"
    },
    {
      "MIGX_id":6,
      "dataIndex":"Date_start_time",
      "header":"Date_start_time"
    },
    {
      "MIGX_id":7,
      "header":"Member_firstname",
      "dataIndex":"Member_firstname",
      "width":"",
      "sortable":true,
      "show_in_grid":1,
      "customrenderer":"",
      "renderer":"",
      "clickaction":"",
      "selectorconfig":"",
      "renderchunktpl":"",
      "renderoptions":"",
      "editor":""
    },
    {
      "MIGX_id":8,
      "header":"Member_name",
      "dataIndex":"Member_name",
      "width":"",
      "sortable":true,
      "show_in_grid":1,
      "customrenderer":"",
      "renderer":"",
      "clickaction":"",
      "selectorconfig":"",
      "renderchunktpl":"",
      "renderoptions":"",
      "editor":""
    },
    {
      "MIGX_id":9,
      "dataIndex":"guestname",
      "header":"guestname"
    }
  ],
  "createdby":1,
  "createdon":"2018-01-24 14:02:59",
  "editedby":1,
  "editedon":"2020-05-18 13:18:01",
  "deleted":0,
  "deletedon":"-1-11-30 00:00:00",
  "deletedby":0,
  "published":1,
  "publishedon":"-1-11-30 00:00:00",
  "publishedby":0,
  "category":""
}