<?php

$xpdo_meta_map = array (
  'xPDOSimpleObject' => 
  array (
    0 => 'fbuchFahrt',
    1 => 'fbuchDestination',
    2 => 'fbuchDate',
    3 => 'fbuchDateNames',
    4 => 'fbuchDateInvited',
    5 => 'fbuchDateComment',
    6 => 'fbuchFahrtNames',
    7 => 'fbuchBoot',
    8 => 'fbuchBootAllowedNames',
    9 => 'fbuchBootComment',
    10 => 'fbuchBootRiggerung',
    11 => 'fbuchBootSetting',
    12 => 'fbuchBootsGattung',
    13 => 'fbuchBootsNutzergruppe',
    14 => 'fbuchBootsNutzergruppenMembers',
    15 => 'fbuchMailinglist',
    16 => 'fbuchMailinglistNames',
    17 => 'fbuchDateType',
    18 => 'mvMemberState',
    19 => 'mvMember',
    20 => 'mvRole',
    21 => 'mvMemberGroup',
    22 => 'mvMemberRoleLink',
    23 => 'mvMemberFilter',
    24 => 'mvExportFilter',
    25 => 'mvMail',
    26 => 'mvFamily',
    27 => 'mvBeitragstyp',
    28 => 'mvMailLog',
    29 => 'mvMailLogRecipient',
    30 => 'mvMimeType',
    31 => 'mvDoorAccesscode',
  ),
);