<?php

$usergroups = [
    [
        'policy'=>'fbuch_instructor',
        'user_group'=>'fbuch_instructor',
        'resource_groups'=>[
            [
                'name'=>'fbuch_instructor'
            ]
        ]
    ],
    [
        'policy'=>'fbuch_user',
        'user_group'=>'fbuch',
        'resource_groups'=>[
            [
                'name'=>'fbuch'
            ]
        ]
    ],
    [
        'policy'=>'fbuch_guest',
        'user_group'=>'fbuch_guest',
        'resource_groups'=>[
            [
                'name'=>'fbuch_guest'
            ]            
        ]
    ],
    [
        'policy'=>'fbuch_clubhome',
        'user_group'=>'fbuch_clubhome',
        'resource_groups'=>[
            [
                'name'=>'fbuch'
            ]
        ]
    ],
    [
        'policy'=>'fbuch_doorcode_manager',
        'user_group'=>'fbuch_doorcode_manager',
        'resource_groups'=>[
            [
                'name'=>'fbuch_doorcode_manager'
            ]
        ]
    ],        
    [
        'policy'=>'mv_member_admin',
        'user_group'=>'mv_member_admin'
    ],
    [
        'policy'=>'mv_competency_editor',
        'user_group'=>'mv_competency_editor'
    ],         
    [
        'policy'=>'Administrator',
        'user_group'=>'Administrator',
        'resource_groups'=>[
            [
                'name'=>'fbuch'
            ],
            [
                'name'=>'fbuch_instructor'
            ],
            [
                'name'=>'Administrator'
            ]               
        ]
    ]
];