<?php

$usergroups = [
    [
        'policy'=>'fbuch_instructor',
        'user_group'=>'fbuch_instructor',
        'resource_groups'=>[
            [
                'name'=>'fbuch_instructor'
            ]
        ]
    ],
    [
        'policy'=>'fbuch_user',
        'user_group'=>'fbuch',
        'resource_groups'=>[
            [
                'name'=>'fbuch'
            ]
        ]
    ],
    [
        'policy'=>'fbuch_guest',
        'user_group'=>'fbuch_guest',
        'resource_groups'=>[
            [
                'name'=>'fbuch_guest'
            ]            
        ]
    ],
    [
        'policy'=>'fbuch_clubhome',
        'user_group'=>'fbuch_clubhome',
        'resource_groups'=>[
            [
                'name'=>'fbuch'
            ]
        ]
    ],
    [
        'policy'=>'Administrator',
        'user_group'=>'Administrator',
        'resource_groups'=>[
            [
                'name'=>'fbuch'
            ],
            [
                'name'=>'fbuch_instructor'
            ],
            [
                'name'=>'Administrator'
            ]               
        ]
    ]
];